### ISSUE TITLE
Retro theme: Font is displayed outside the app border

### ISSUE THREAD

**Issue by Robert27** [neuland-ingolstadt/neuland.app-ios#5]
### Description
Retro Theme font is displayed outside the app boundary on small devices, such as the iPhone SE.

### Screenshots
[Simulator Screen Shot - iPhone SE (2nd generation) - 2021-11-30](https://user-images.githubusercontent.com/53063597/144083032-b84c0dfc-aed9-48d3-b4b1-e79a6f93fed5.png)
[Simulator Screen Shot - iPhone 13 Pro Max - 2021-11-30](https://user-images.githubusercontent.com/53063597/144083130-7172569d-63ad-4314-a030-bfebb1cc1048.png)

**Comment by M4GNV5** [comment]
I do not think this is a iOS-App specific bug. It also exists when using the web version of the App on small devices such as my iPhone 12 mini:

![image](https://user-images.githubusercontent.com/5504713/144098193-7b0de01b-6a82-4b7f-9fdc-7530f26042f8.png)
